[project]
name = "mcp-cb"
version = "0.1.0"
description = "Telegram chatbot with ChatGPT and MCP server integration for currency rates"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyTelegramBotAPI>=4.14.0",
    "openai>=1.12.0",
    "requests>=2.31.0",
    "mcp",
]
